### ISSUE TITLE
What about the performance on the MNIST dataset

### ISSUE THREAD

**Issue by 1999kevin** [thorinf/consistency-mnist#1]
What about the performance on the MNIST dataset？ And waht about the GPU comsumption?

**Comment by thorinf** [comment]
I'm updating the readme now. Here is an output after 100 epochs:

<p align="center">
  <img src="https://user-images.githubusercontent.com/91201457/233678372-d13a53bd-ad49-450b-8eb7-b8ba32f8c72a.gif">
</p>

If you add use the same noise for every iteration at sampling then the images do not switch between different numbers as much. This is the intended property of 'self-consistency' from the paper. Generations on the same trajectory producing the same sample. However the multi-step sampler algorithm in the paper does add different noise each iteration. Really up to you which you prefer. 

The GPU consumption is pretty low, I have only 2GB of VRAM. It could probably be a lot better with a smaller NN - I think the UNet I've used is too big.

**Comment by 1999kevin** [comment]
Thanks for your quick answers. The performance is pretty good. I find that you use L2 loss. I guess this will also reduce the GPU consumption

**Comment by thorinf** [comment]
Here is sampling where the same noise is injected at every iteration. 

<p align="center">
  <img src="https://user-images.githubusercontent.com/91201457/233682080-a46e845d-7a46-4265-9ae1-d76efd3fa69b.gif">
</p>

Yeah I think L2 is fine for this task. The goal is the implementation is A) for me to learn, and B) create something minimal.

**Comment by 1999kevin** [comment]
So appreciate of your implementation on MNIST!

**Comment by thorinf** [comment]
Please give the project a watch or a star if you can. Currently looking for work and a bit of Github exposure might help.

**Comment by 1999kevin** [comment]
Sure, I'm glad to  help.
