### ISSUE TITLE
Is the label been taken as the condition ?

### ISSUE THREAD

**Issue by yyua8222** [thorinf/consistency-mnist#3]
Thanks so much for the instant implementation, the result seems perfect!  However, I just had a quick scan of the code but find that the label variable is not actually used during training?  It seems that the label has been passed to the loss_t function on line 151 but did not be applied to anything or the denoise function then? Or am I wrong and miss something?  thanks

**Comment by thorinf** [comment]
No, that's completely right. I have not added a conditional label. This was intentional, but it would be fairly trivial to add it in and I should probably make it an option.

**Comment by yyua8222** [comment]
Thanks for the quick reply! Cheers!

**Comment by thorinf** [comment]
If you do wish to add a conditional vector then it may be a good idea to give it a dropout probability. This was the model will learn conditional and unconditional generation.

**Comment by thorinf** [comment]
I will do this now.

**Comment by thorinf** [comment]
Done
